"""Generates a seamless short-turf texture set and the tiling for a zone's
lawn materials.

    python make_turf.py <out folder with <name>.gltf> [--size 2048]
    python make_turf.py <out folder> --source <unzipped ambientCG folder>

Writes turf_basecolor.png, turf_normal.png, turf_mr.png (glTF layout:
G = roughness, B = metallic) and turf.json, which maps each lawn material
to the UV scale that makes one turf repeat cover TILE_METERS. The Unreal
setup script swaps these into the imported lawn materials.

With --source, a downloaded PBR set is used instead (ambientCG layout:
*_Color, *_NormalGL, *_Roughness, optional *_AmbientOcclusion; CC0).
Otherwise the texture is drawn, not generated by AI: thousands of short blades on a
canvas that wraps at the edges (so it tiles seamlessly), over a darker
thatch layer, with a height map turned into the normal map.
"""
import glob
import json
import math
import os
import sys

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

TILE_METERS = 1.5
LAWN_NAMES = ("grass_plate", "grass_freshcut", "lawn", "turf")
BLADES_PER_PX = 0.04        # blades per pixel of the final texture


def tile_noise(rng, size, scale):
    """Tileable smooth noise in 0..1 (FFT low-pass of white noise)."""
    f = np.fft.fft2(rng.standard_normal((size, size)))
    fy = np.fft.fftfreq(size)[:, None]
    fx = np.fft.fftfreq(size)[None, :]
    f *= np.exp(-(fx * fx + fy * fy) * (size / scale) ** 2)
    n = np.real(np.fft.ifft2(f))
    return (n - n.min()) / (np.ptp(n) or 1)


def make_turf(size, rng):
    ss = size * 2                                  # draw at 2x, downsample
    patch = tile_noise(rng, ss, 6)                 # large patches
    fine = tile_noise(rng, ss, 90)
    # thatch / soil underneath: dark olive-brown
    base = np.stack([0.16 + 0.05 * fine, 0.20 + 0.06 * fine,
                     0.08 + 0.03 * fine], -1)
    col = Image.fromarray((base * 255).astype(np.uint8))
    hgt = Image.fromarray((fine * 40).astype(np.uint8))
    dc, dh = ImageDraw.Draw(col), ImageDraw.Draw(hgt)
    n = int(BLADES_PER_PX * size * size)
    xs = rng.uniform(0, ss, n)
    ys = rng.uniform(0, ss, n)
    order = np.argsort(rng.uniform(size=n))       # random overlap order
    for i in order:
        x, y = xs[i], ys[i]
        p = patch[int(y) % ss, int(x) % ss]
        ang = rng.uniform(0, 2 * math.pi)
        length = rng.uniform(10, 26) * (0.8 + 0.4 * p)
        width = rng.uniform(2.2, 4.0)
        tall = rng.uniform(0.4, 1.0)                # how much it stands up
        # colour: spring green to yellow-green, lighter when taller
        hue = rng.uniform(-1, 1)
        light = 0.55 + 0.45 * tall
        r = (0.23 + 0.10 * hue * (hue > 0) + 0.05 * (1 - p)) * light
        g = (0.47 + 0.08 * p + 0.06 * rng.uniform(-1, 1)) * light
        b = (0.12 + 0.03 * rng.uniform(-1, 1)) * light
        ex, ey = x + math.cos(ang) * length, y + math.sin(ang) * length
        segs = 4
        for s in range(segs):                       # taper toward the tip
            t0, t1 = s / segs, (s + 1) / segs
            ax, ay = x + (ex - x) * t0, y + (ey - y) * t0
            bx, by = x + (ex - x) * t1, y + (ey - y) * t1
            w = max(1, int(round(width * (1 - 0.7 * t0))))
            k = 0.75 + 0.35 * t1                    # base darker, tip lit
            c = tuple(int(min(1, v * k) * 255) for v in (r, g, b))
            hv = int(60 + 190 * tall * t1)
            for ox in (0, -ss, ss):                 # wrap across edges
                for oy in (0, -ss, ss):
                    if ox and not (min(ax, bx) < 30 or max(ax, bx) > ss - 30):
                        continue
                    if oy and not (min(ay, by) < 30 or max(ay, by) > ss - 30):
                        continue
                    seg = (ax + ox, ay + oy, bx + ox, by + oy)
                    dc.line(seg, fill=c, width=w)
                    dh.line(seg, fill=hv, width=w)
    col = col.resize((size, size), Image.LANCZOS)
    hgt = hgt.filter(ImageFilter.GaussianBlur(1.2)).resize((size, size),
                                                           Image.LANCZOS)
    h = np.asarray(hgt, dtype=np.float32) / 255.0
    # ambient occlusion: darken where the canopy is low
    blur = np.asarray(hgt.filter(ImageFilter.GaussianBlur(6)),
                      dtype=np.float32) / 255.0
    ao = np.clip(0.55 + 0.6 * (h - blur) + 0.45 * blur, 0.45, 1.0)
    c = np.asarray(col, dtype=np.float32) * ao[..., None]
    basecolor = Image.fromarray(np.clip(c, 0, 255).astype(np.uint8))
    # normal map from the height map (wrapping gradients), OpenGL +Y
    strength = 6.0
    dx = (np.roll(h, -1, 1) - np.roll(h, 1, 1)) * strength
    dy = (np.roll(h, -1, 0) - np.roll(h, 1, 0)) * strength
    nz = np.ones_like(h)
    ln = np.sqrt(dx * dx + dy * dy + 1)
    nrm = np.stack([-dx / ln, dy / ln, nz / ln], -1)
    normal = Image.fromarray(((nrm * 0.5 + 0.5) * 255).astype(np.uint8))
    # roughness: grass is matte, slightly glossier on the tallest blades
    rough = np.clip(0.92 - 0.15 * h, 0.7, 0.95)
    mr = np.stack([np.zeros_like(h), rough, np.zeros_like(h)], -1)
    mr_img = Image.fromarray((mr * 255).astype(np.uint8))
    return basecolor, normal, mr_img


def from_source(folder, size):
    """Turf set from a downloaded PBR texture (ambientCG naming)."""
    def find(*keys):
        for f in sorted(os.listdir(folder)):
            low = f.lower()
            if all(k in low for k in keys) and low.endswith((".jpg", ".png")):
                return Image.open(os.path.join(folder, f))
        return None
    color = find("_color")
    normal = find("_normalgl")
    rough = find("_roughness")
    ao = find("_ambientocclusion")
    if color is None or normal is None:
        raise SystemExit("no *_Color / *_NormalGL maps in " + folder)
    color = color.convert("RGB").resize((size, size), Image.LANCZOS)
    c = np.asarray(color, dtype=np.float32)
    if ao is not None:
        a = np.asarray(ao.convert("L").resize((size, size), Image.LANCZOS),
                       dtype=np.float32) / 255.0
        c *= (0.35 + 0.65 * a)[..., None]       # keep some AO in the colour
    basecolor = Image.fromarray(np.clip(c, 0, 255).astype(np.uint8))
    normal = normal.convert("RGB").resize((size, size), Image.LANCZOS)
    r = (np.asarray(rough.convert("L").resize((size, size), Image.LANCZOS),
                    dtype=np.float32) / 255.0) if rough is not None         else np.full((size, size), 0.9, np.float32)
    z = np.zeros_like(r)
    mr = Image.fromarray((np.stack([z, r, z], -1) * 255).astype(np.uint8))
    return basecolor, normal, mr


def lawn_scales(out_dir):
    """UV scale per lawn material so a turf repeat covers TILE_METERS."""
    gltf = glob.glob(os.path.join(out_dir, "*.gltf"))[0]
    g = json.load(open(gltf))
    blob = open(os.path.splitext(gltf)[0] + ".bin", "rb").read()

    def acc(i, comps, dt):
        a = g["accessors"][i]
        v = g["bufferViews"][a["bufferView"]]
        arr = np.frombuffer(blob, dtype=dt, count=a["count"] * comps,
                            offset=v["byteOffset"])
        return arr.reshape(-1, comps) if comps > 1 else arr

    ratios = {}
    for m in g["meshes"]:
        for p in m["primitives"]:
            mat = g["materials"][p["material"]]
            name = mat["name"]
            if not any(k in name.lower() for k in LAWN_NAMES):
                continue
            if mat.get("alphaMode") in ("MASK", "BLEND"):
                continue        # tufts and cards keep their own textures
            pos = acc(p["attributes"]["POSITION"], 3, np.float32)
            uv = acc(p["attributes"]["TEXCOORD_0"], 2, np.float32)
            tri = acc(p["indices"], 1, np.uint32).reshape(-1, 3)[:3000]
            dw = np.linalg.norm(pos[tri[:, 0]] - pos[tri[:, 1]], axis=1)
            du = np.linalg.norm(uv[tri[:, 0]] - uv[tri[:, 1]], axis=1)
            ok = (du > 1e-4) & (dw > 0.05)
            tex = mat["pbrMetallicRoughness"].get("baseColorTexture", {})
            pre = tex.get("extensions", {}).get(
                "KHR_texture_transform", {}).get("scale", [1, 1])[0]
            ratios.setdefault(name, ([], pre))[0].extend(dw[ok] / du[ok])
    out = {}
    for name, (r, pre) in ratios.items():
        if r:
            out[name.replace(".", "_")] = round(
                float(np.median(r)) / TILE_METERS, 2)
    return out


def main():
    out_dir = sys.argv[1]
    size = int(sys.argv[sys.argv.index("--size") + 1]) \
        if "--size" in sys.argv else 2048
    if "--source" in sys.argv:
        basecolor, normal, mr = from_source(
            sys.argv[sys.argv.index("--source") + 1], size)
    else:
        basecolor, normal, mr = make_turf(size, np.random.default_rng(1977))
    basecolor.save(os.path.join(out_dir, "turf_basecolor.png"))
    normal.save(os.path.join(out_dir, "turf_normal.png"))
    mr.save(os.path.join(out_dir, "turf_mr.png"))
    scales = lawn_scales(out_dir)
    with open(os.path.join(out_dir, "turf.json"), "w") as f:
        json.dump({"tile_meters": TILE_METERS, "materials": scales}, f,
                  indent=1)
    print("turf textures %dpx; lawn materials: %s" % (size, scales))


if __name__ == "__main__":
    main()
